# Generated by Django 4.1.7 on 2023-04-05 13:17

from django.db import migrations, models
import shelter_v11.animal_photos.validators


class Migration(migrations.Migration):

    dependencies = [
        ('animal_photos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='animalphotos',
            old_name='tagged_pets',
            new_name='tagged_animals',
        ),
        migrations.AlterField(
            model_name='animalphotos',
            name='photo',
            field=models.ImageField(blank=True, upload_to='animal_photos/', validators=[shelter_v11.animal_photos.validators.validate_file_less_than_5mb]),
        ),
    ]
