# Generated by Django 4.2 on 2023-05-03 22:52

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import greatApp.commons.model_mixins
import greatApp.commons.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("animals", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnimalPhotos",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        upload_to="animal_photos/",
                        validators=[
                            greatApp.commons.validators.validate_file_less_than_5mb
                        ],
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        validators=[django.core.validators.MinLengthValidator(10)],
                    ),
                ),
                ("location", models.CharField(blank=True, max_length=30, null=True)),
                ("publication_date", models.DateField(auto_now=True)),
                (
                    "tagged_animals",
                    models.ManyToManyField(blank=True, to="animals.animals"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            bases=(greatApp.commons.model_mixins.StrFromFieldsMixin, models.Model),
        ),
    ]
