# Generated by Django 4.1.7 on 2023-04-18 21:08

from django.db import migrations, models
import shelter_v11.commons.model_mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('personal_photo', models.URLField()),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
            ],
            bases=(shelter_v11.commons.model_mixins.StrFromFieldsMixin, models.Model),
        ),
    ]
