version: '3.8'

services:
  web:
    build: ./greatApp
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./greatApp/:/usr/src/app/
    ports:
      - 8000:8000
    env_file:
      - ./greatApp/envs/.env
    depends_on:
      - postgres
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: Passw0rd465
      POSTGRES_USER: greatappuser5
      POSTGRES_DB: postgres
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./postgresql:/var/lib/postgresql/data