# Generated by Django 4.2 on 2023-05-03 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import greatApp.commons.model_mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Animals",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30)),
                ("personal_photo", models.URLField()),
                ("slug", models.SlugField(blank=True, unique=True)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            bases=(greatApp.commons.model_mixins.StrFromFieldsMixin, models.Model),
        ),
    ]
